[package]
name = "attractor"
version = "0.1.0"
authors = ["sabjorn <info@sabjorn.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.13.1"
libc = "0.2"
minifb = "0.19.2"
